### PR TITLE
Refactor rich cooling tower1 spd

### PR DESCRIPTION
**Pull request by Myoldmopar**

### CODE REVIEW

**Comment by mjwitte** [comment]
@Myoldmopar Remind me why we didn't include runflag as an argument to simulate?  Seems rather basic, especially from the standpoint of a clean unit test path.

**Comment by Myoldmopar** [comment]
We totally can.  We were trying to keep it minimal, but I think given the number of components that want to use it, we should do it.  I'll try to add that this morning and flesh it out to the components already merged into develop over here.

**Comment by mjwitte** [comment]
@Myoldmopar Just opening a discussion.  @EnergyArchmage @rraustad Opinions on adding RunFlag back in as an argument to simulate?

**Comment by rraustad** [comment]
I think it's less intrusive as a function argument then going out and grabbing it.

**Comment by EnergyArchmage** [comment]
I think it does make sense to have it as an argument.

**Pull request closed without merging**
