### PR TITLE
Hp water ef cooling

### PR DESCRIPTION
**Pull request by kbenne**

### CODE REVIEW

**Comment by Myoldmopar** [comment]
REJECTED! :-1:

**Comment by Myoldmopar** [comment]
Emoji reinforcements have been brought in :nail_care: :dancers: :christmas_tree: :chart_with_downwards_trend:

**Comment by kbenne** [comment]
Rejected on what grounds! Objection!

**Comment by Myoldmopar** [comment]
You can't handle the truth!!!

**Comment by Myoldmopar** [comment]
This whole courtroom is out of order!

**Pull request closed without merging**
